#!/bin/sh
sudo service nginx onestop
sudo rm -f /usr/local/etc/nginx/sites-enabled/*
rm -rf /home/judge/hw4/4-1/data/static/*

while true; do
    pid_list=$(ps aux | grep 'node' | awk '{printf $2"\n"}')
    line=$(echo -e "$pid_list" | wc -l)
    if [ $line -le 1 ]; then
        break
    fi
    pid=$(echo "$pid_list" | head -n 1)
    echo "killing $pid"
    sudo kill "$pid"
done

